# MySQL configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/hotel_22?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# MongoDB configuration
quarkus.mongodb.connection-string=mongodb+srv://levanchinh13052005_db_user:ZnNNmXhZq98owuOC@cluster0.j9w8jmh.mongodb.net/?appName=Cluster0
quarkus.mongodb.database=hotel_22

# JWT configuration
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=https://example.com/issuer
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
smallrye.jwt.new-token.issuer=https://example.com/issuer
smallrye.jwt.new-token.audience=https://example.com/audience

# HTTP authorization
quarkus.http.auth.permission.public.paths=/auth/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Development convenience
quarkus.http.port=8080
